// Objective-C API for talking to RewindPS4/proxy_server Go package.
//   gobind -lang=objc RewindPS4/proxy_server
//
// File is generated by gobind. Do not edit.

#ifndef __Rewind_H__
#define __Rewind_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class RewindPackage;
@class RewindParamsfo;
@class RewindProxyInfo;
@class RewindTag;
@class RewindTitlePatch;
@class RewindXMLDetails;

@interface RewindPackage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull version;
// skipped field Package.Paramsfo with unsupported type: RewindPS4/proxy_server.Paramsfo

@property (nonatomic) NSString* _Nonnull manifestURL;
@property (nonatomic) NSString* _Nonnull contentID;
@end

@interface RewindParamsfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull title;
@end

@interface RewindProxyInfo : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull ip;
@property (nonatomic) NSString* _Nonnull port;
@end

@interface RewindTag : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Tag.Package with unsupported type: RewindPS4/proxy_server.Package

@end

@interface RewindTitlePatch : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field TitlePatch.XMLName with unsupported type: encoding/xml.Name

@property (nonatomic) NSString* _Nonnull titleID;
// skipped field TitlePatch.Tag with unsupported type: RewindPS4/proxy_server.Tag

@end

@interface RewindXMLDetails : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull cusa;
@property (nonatomic) NSString* _Nonnull gameName;
@property (nonatomic) NSString* _Nonnull lastVersion;
@property (nonatomic) NSString* _Nonnull lastJSONURL;
@property (nonatomic) NSString* _Nonnull region;
@end

/**
 * adjust the client activity status
 */
FOUNDATION_EXPORT void RewindCheckClientActivity(void);

FOUNDATION_EXPORT BOOL RewindCheckPort(long port);

FOUNDATION_EXPORT NSString* _Nonnull RewindCheckXML(NSString* _Nullable xmlURL);

// skipped function ClientRequest with unsupported parameter or return types


// skipped function ClientStatus with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull RewindDetails(NSString* _Nullable inputJSON, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull RewindDetector(NSString* _Nullable userAgent);

FOUNDATION_EXPORT NSString* _Nonnull RewindExtractCUSA(NSString* _Nullable url);

FOUNDATION_EXPORT NSString* _Nonnull RewindExtractVersion(NSString* _Nullable url);

FOUNDATION_EXPORT NSString* _Nonnull RewindExtractXML(NSString* _Nullable xmlData, NSError* _Nullable* _Nullable error);

/**
 * send the server start failure info to the frontend
 */
FOUNDATION_EXPORT NSString* _Nonnull RewindGetLastServerError(void);

// skipped function InitProxy with unsupported parameter or return types


FOUNDATION_EXPORT BOOL RewindIsValidJSONURL(NSString* _Nullable url);

FOUNDATION_EXPORT NSString* _Nonnull RewindLocalIP(void);

/**
 * log record
 */
FOUNDATION_EXPORT void RewindLogger(NSString* _Nullable logType, NSString* _Nullable logContent);

FOUNDATION_EXPORT NSString* _Nonnull RewindMapper(NSString* _Nullable targetJSON, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL RewindOpenBrowser(NSString* _Nullable url, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void RewindOtherLog(long num);

FOUNDATION_EXPORT NSString* _Nonnull RewindPSNXML(NSString* _Nullable CUSA);

// skipped function SendLogs with unsupported parameter or return types


/**
 * select mode to set url mapping or block update
update the urlMap or blockUpdate's status based on the mode
 */
FOUNDATION_EXPORT NSString* _Nonnull RewindSetMode(long mode, NSString* _Nullable jsonLink, NSError* _Nullable* _Nullable error);

// skipped function SetupCORS with unsupported parameter or return types


/**
 * get the size of the .pkg file
 */
FOUNDATION_EXPORT NSString* _Nonnull RewindSizer(NSString* _Nullable pkgURL, NSError* _Nullable* _Nullable error);

/**
 * log server,transfer the logs to the frontend
browse logs ： http://localhost:29090/logs
 */
FOUNDATION_EXPORT void RewindStartLogServer(void);

/**
 * start proxy server.  already use setmode to set url mapping or block update
 */
FOUNDATION_EXPORT void RewindStartProxy(NSString* _Nullable port);

FOUNDATION_EXPORT void RewindStopProxy(void);

FOUNDATION_EXPORT NSString* _Nonnull RewindTitleMetadataInfo(NSString* _Nullable jsonLink, NSError* _Nullable* _Nullable error);

#endif
