
// Objective-C API for talking to the following Go packages
//
//	RewindPS4/proxy_server
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ProxyServer_FRAMEWORK_H__
#define __ProxyServer_FRAMEWORK_H__

#include "Rewind.objc.h"
#include "Universe.objc.h"

#endif
